name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image (Single User)
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        target: single-user
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/ai-chat-app:single-user-latest
          ${{ secrets.DOCKER_USERNAME }}/ai-chat-app:single-user-1.0.${{ github.run_number }}      

    - name: Build and push Docker image (Multi User)
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        target: multi-user
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/ai-chat-app:multi-user-latest
          ${{ secrets.DOCKER_USERNAME }}/ai-chat-app:multi-user-1.0.${{ github.run_number }}      